networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge
services:
  mysql:
    build:
      args:
        MYSQL_VERSION: latest
      context: ../npfw/mysql
    environment:
      MYSQL_DATABASE: acat_main
      MYSQL_PASSWORD: mysql
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: mysql
      TZ: UTC
    networks:
      backend: null
    ports:
    - 3306:3306/tcp
    volumes:
    - /root/.laradock/data/mysql:/var/lib/mysql:rw
    - ../npfw/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:rw
  nginx:
    build:
      args:
        CHANGE_SOURCE: "false"
        PHP_UPSTREAM_CONTAINER: php-fpm
        PHP_UPSTREAM_PORT: '9000'
        http_proxy: ''
        https_proxy: ''
        no_proxy: ''
      context: ../npfw/nginx
    depends_on:
    - php-fpm
    networks:
      backend: null
      frontend: null
    ports:
    - 80:80/tcp
    - 443:443/tcp
    - 81:81/tcp
    volumes:
    - ../src:/var/www:cached
    - ../npfw/logs/nginx:/var/log/nginx:rw
    - ../npfw/nginx/sites:/etc/nginx/sites-available:rw
    - ../npfw/nginx/ssl:/etc/nginx/ssl:rw
  php-fpm:
    build:
      args:
        ADDITIONAL_LOCALES: '"en_US.UTF-8 es_ES.UTF-8 fr_FR.UTF-8"'
        BASE_IMAGE_TAG_PREFIX: latest
        CHANGE_SOURCE: "false"
        INSTALL_ADDITIONAL_LOCALES: "false"
        INSTALL_AEROSPIKE: "false"
        INSTALL_AMQP: "false"
        INSTALL_APCU: "false"
        INSTALL_BCMATH: "true"
        INSTALL_BLACKFIRE: "false"
        INSTALL_BZ2: "false"
        INSTALL_CACHETOOL: "false"
        INSTALL_CALENDAR: "false"
        INSTALL_CASSANDRA: "false"
        INSTALL_EXIF: "false"
        INSTALL_FAKETIME: "false"
        INSTALL_FFMPEG: "false"
        INSTALL_GEARMAN: "false"
        INSTALL_GETTEXT: "false"
        INSTALL_GHOSTSCRIPT: "false"
        INSTALL_GMP: "false"
        INSTALL_IMAGEMAGICK: "true"
        INSTALL_IMAGE_OPTIMIZERS: "true"
        INSTALL_IMAP: "false"
        INSTALL_INTL: "true"
        INSTALL_IONCUBE: "false"
        INSTALL_LDAP: "false"
        INSTALL_MAILPARSE: "false"
        INSTALL_MEMCACHED: "false"
        INSTALL_MONGO: "false"
        INSTALL_MSSQL: "false"
        INSTALL_MYSQLI: "true"
        INSTALL_MYSQL_CLIENT: "false"
        INSTALL_OCI8: "false"
        INSTALL_OPCACHE: "true"
        INSTALL_PCNTL: "false"
        INSTALL_PCOV: "false"
        INSTALL_PGSQL: "false"
        INSTALL_PG_CLIENT: "false"
        INSTALL_PHALCON: "false"
        INSTALL_PHPDBG: "false"
        INSTALL_PHPREDIS: "false"
        INSTALL_PING: "false"
        INSTALL_POSTGIS: "false"
        INSTALL_RDKAFKA: "false"
        INSTALL_SMB: "false"
        INSTALL_SOAP: "false"
        INSTALL_SSH2: "false"
        INSTALL_SSHPASS: "false"
        INSTALL_SWOOLE: "false"
        INSTALL_TAINT: "false"
        INSTALL_WKHTMLTOPDF: "false"
        INSTALL_XDEBUG: "false"
        INSTALL_XHPROF: "false"
        INSTALL_XSL: "false"
        INSTALL_YAML: "false"
        LARADOCK_PHALCON_VERSION: 3.4.5
        LARADOCK_PHP_VERSION: '7.4'
        LOCALE: POSIX
        PGID: '1000'
        PUID: '1000'
        http_proxy: ''
        https_proxy: ''
        no_proxy: ''
      context: ../npfw/php-fpm
    depends_on:
    - workspace
    environment:
      FAKETIME: '-0'
      PHP_IDE_CONFIG: serverName=laradock
    expose:
    - '9000'
    networks:
      backend: null
    volumes:
    - ../npfw/php-fpm/php7.4.ini:/usr/local/etc/php/php.ini:rw
    - ../src:/var/www:cached
  php-worker:
    build:
      args:
        CHANGE_SOURCE: "false"
        INSTALL_AMQP: "false"
        INSTALL_BCMATH: "false"
        INSTALL_BZ2: "false"
        INSTALL_CASSANDRA: "false"
        INSTALL_FFMPEG: "false"
        INSTALL_GD: "false"
        INSTALL_GEARMAN: "false"
        INSTALL_GHOSTSCRIPT: "false"
        INSTALL_GMP: "false"
        INSTALL_MYSQL_CLIENT: "false"
        INSTALL_PGSQL: "false"
        INSTALL_PHALCON: "false"
        INSTALL_REDIS: "false"
        INSTALL_SOAP: "false"
        INSTALL_SWOOLE: "false"
        INSTALL_TAINT: "false"
        INSTALL_ZIP_ARCHIVE: "false"
        LARADOCK_PHP_VERSION: '7.4'
        PGID: '1000'
        PHALCON_VERSION: 3.4.5
        PUID: '1000'
      context: ../npfw/php-worker
    depends_on:
    - workspace
    networks:
      backend: null
    volumes:
    - ../src:/var/www:cached
    - ../npfw/php-worker/supervisord.d:/etc/supervisord.d:rw
  phpmyadmin:
    build:
      context: ../npfw/phpmyadmin
    depends_on:
    - mysql
    environment:
      MYSQL_PASSWORD: mysql
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: mysql
      PMA_ARBITRARY: '1'
    networks:
      backend: null
      frontend: null
    ports:
    - 8081:80/tcp
  workspace:
    build:
      args:
        AST_VERSION: 1.0.3
        BASE_IMAGE_TAG_PREFIX: latest
        BLACKFIRE_CLIENT_ID: '"<client_id>"'
        BLACKFIRE_CLIENT_TOKEN: '"<client_token>"'
        CHANGE_SOURCE: "false"
        CHROME_DRIVER_VERSION: '2.42'
        COMPOSER_AUTH: "false"
        COMPOSER_GLOBAL_INSTALL: "false"
        COMPOSER_REPO_PACKAGIST: ''
        DRUSH_VERSION: 8.1.17
        INSTALL_AEROSPIKE: "false"
        INSTALL_AMQP: "false"
        INSTALL_AST: "false"
        INSTALL_BLACKFIRE: "false"
        INSTALL_BZ2: "false"
        INSTALL_CASSANDRA: "false"
        INSTALL_DEPLOYER: "false"
        INSTALL_DRUPAL_CONSOLE: "false"
        INSTALL_DRUSH: "false"
        INSTALL_DUSK_DEPS: "false"
        INSTALL_FFMPEG: "false"
        INSTALL_FSWATCH: "false"
        INSTALL_GEARMAN: "false"
        INSTALL_GIT_PROMPT: "false"
        INSTALL_GMP: "false"
        INSTALL_GNU_PARALLEL: "false"
        INSTALL_IMAGEMAGICK: "false"
        INSTALL_IMAGE_OPTIMIZERS: "false"
        INSTALL_IMAP: "false"
        INSTALL_INOTIFY: "false"
        INSTALL_IONCUBE: "false"
        INSTALL_LARAVEL_ENVOY: "false"
        INSTALL_LARAVEL_INSTALLER: "false"
        INSTALL_LDAP: "false"
        INSTALL_LIBPNG: "false"
        INSTALL_LINUXBREW: "false"
        INSTALL_MAILPARSE: "false"
        INSTALL_MC: "false"
        INSTALL_MONGO: "false"
        INSTALL_MSSQL: "false"
        INSTALL_MYSQL_CLIENT: "false"
        INSTALL_NODE: "false"
        INSTALL_NPM_ANGULAR_CLI: "false"
        INSTALL_NPM_BOWER: "false"
        INSTALL_NPM_GULP: "false"
        INSTALL_NPM_VUE_CLI: "false"
        INSTALL_OCI8: "false"
        INSTALL_PCOV: "false"
        INSTALL_PG_CLIENT: "false"
        INSTALL_PHALCON: "false"
        INSTALL_PHPDBG: "false"
        INSTALL_PHPREDIS: "false"
        INSTALL_PING: "false"
        INSTALL_POWERLINE: "false"
        INSTALL_PRESTISSIMO: "false"
        INSTALL_PYTHON: "false"
        INSTALL_SMB: "false"
        INSTALL_SOAP: "false"
        INSTALL_SSH2: "false"
        INSTALL_SSHPASS: "false"
        INSTALL_SUBVERSION: "false"
        INSTALL_SUPERVISOR: "false"
        INSTALL_SWOOLE: "false"
        INSTALL_SYMFONY: "false"
        INSTALL_TAINT: "false"
        INSTALL_TERRAFORM: "false"
        INSTALL_V8JS: "false"
        INSTALL_WKHTMLTOPDF: "false"
        INSTALL_WORKSPACE_SSH: "false"
        INSTALL_WP_CLI: "false"
        INSTALL_XDEBUG: "false"
        INSTALL_XSL: "false"
        INSTALL_YAML: "false"
        INSTALL_YARN: "false"
        LARADOCK_PHALCON_VERSION: 3.4.5
        LARADOCK_PHP_VERSION: '7.4'
        NODE_VERSION: node
        NPM_REGISTRY: ''
        NVM_NODEJS_ORG_MIRROR: ''
        PGID: '1000'
        PUID: '1000'
        SHELL_OH_MY_ZSH: "false"
        TZ: UTC
        UBUNTU_SOURCE: aliyun
        YARN_VERSION: latest
        http_proxy: ''
        https_proxy: ''
        no_proxy: ''
      context: ../npfw/workspace
    environment:
      PHP_IDE_CONFIG: serverName=laradock
    networks:
      backend: null
      frontend: null
    ports:
    - 2222:22/tcp
    - 3000:3000/tcp
    - 3001:3001/tcp
    - 8080:8080/tcp
    - 8001:8000/tcp
    tty: true
    volumes:
    - ../src:/var/www:cached
    - ../npfw/php-worker/supervisord.d:/etc/supervisord.d:rw
version: '3.0'
volumes:
  mysql:
    driver: local
  neo4j:
    driver: local
  phpmyadmin:
    driver: local

